<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Email  Please enter a valid email address</name>
   <tag></tag>
   <elementGuidId>eadb1639-3437-44f4-9c09-c98dccf09ac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='item-vfb-14']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item-vfb-14</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ce99fd69-b38f-45ec-b0ad-08881524c8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-item vfb-item-email  </value>
      <webElementGuid>40a486ee-1aa8-49d8-b2e6-50314bbf4890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item-vfb-14</value>
      <webElementGuid>3a76958f-bc4f-4b43-937c-ff604ecb6ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email  *Please enter a valid email address.</value>
      <webElementGuid>4a5b6494-63aa-4922-8dd7-d42536ab0304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-vfb-14&quot;)</value>
      <webElementGuid>93bd98e3-2f0b-4686-acca-435f80478108</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-14']</value>
      <webElementGuid>bc12d994-9d96-435b-9e7a-5d638ad65cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='item-vfb-1']/ul/li[5]</value>
      <webElementGuid>e8fd4a5c-642b-43fd-b4ca-aa926ac653f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::li[1]</value>
      <webElementGuid>4a2d63d9-3830-4745-b72c-6852cc2cafa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal / Zip Code'])[1]/following::li[1]</value>
      <webElementGuid>e27261da-5ab6-4520-945d-697bb66598d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/ul/li[5]</value>
      <webElementGuid>0fa3e955-97b0-4ec5-a3e8-f85624f661ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'item-vfb-14' and (text() = 'Email  *Please enter a valid email address.' or . = 'Email  *Please enter a valid email address.')]</value>
      <webElementGuid>d49ea07f-6be8-4b72-aa6a-fc86d1fc6e91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
