<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Email</name>
   <tag></tag>
   <elementGuidId>43090fe7-5670-4c8f-a20a-9fee7a7f40b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='item-vfb-14']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item-vfb-14</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d03f477f-b902-4d64-a4db-50f55721e569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-item vfb-item-email  </value>
      <webElementGuid>af5a6fe3-d8d7-4121-b992-aa89201115e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item-vfb-14</value>
      <webElementGuid>42df472a-b065-4f46-aeea-731ff7769e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email  *</value>
      <webElementGuid>557f6dd5-4c48-4f89-a6e4-7b4754045421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-vfb-14&quot;)</value>
      <webElementGuid>f1a52a13-78c1-4cb2-b535-5442f0a0af67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-14']</value>
      <webElementGuid>726a11de-ed10-470e-a4b5-c0a457d6b49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='item-vfb-1']/ul/li[5]</value>
      <webElementGuid>5e2915eb-525c-4c43-b90c-9306653c46fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::li[1]</value>
      <webElementGuid>4361b04f-97a7-497a-8196-6ef40211e3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal / Zip Code'])[1]/following::li[1]</value>
      <webElementGuid>72f2aea2-a885-480b-92e3-7be2e98ba4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/ul/li[5]</value>
      <webElementGuid>a65d4307-ac55-4d5d-b2fd-56db1c860ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'item-vfb-14' and (text() = 'Email  *' or . = 'Email  *')]</value>
      <webElementGuid>7f0cd3ee-79d0-422c-b11e-20623085b4d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
